---
- name: Prepare the hosts to be a k8s node
  hosts: k8s-ctrl
  become: true
  become_user: root
  tasks:
    - name: Download the latest cilium executable and extract the runtime
      ansible.builtin.script:
        cmd: /home/xtophe/automate/ansible/k8s-deploy-ansible/script-4-download-cilium.sh
        creates: /home/ansible/.cilium.installed

    - name: Install cilium
      ansible.builtin.command:
        cmd: cilium install --version 1.15.6
